version: '3.8'

services:
  app:
    container_name: app-dev
    image: app-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000

  test:
    build:
      context: .
    environment:
      - CI=true
    command: yarn test
